[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
ModalDecisionTrees = "e54bda2e-c571-11ec-9d64-0242ac120002"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sole = "7b3b3b3f-8b15-4a80-a798-b383498bc2cf"
SoleLogics = "b002da8f-3cb3-4d91-bbe3-2953433912b5"
SoleModels = "4249d9c7-3290-4ddd-961c-e1d3ec2467f8"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Sole = "0.3"
